# Redis 호스트 및 포트
spring:
  data:
    redis:
      port: 6379
      host: localhost

jwt:
  secret: abcdefghijklmnopqrstuvffefefaefaefaefaefaefaefafefafeaefaefafefadfdasfadfafdfdaffafdasdfadfadfadfadsfasdfadfafdfasdf
  accessExpiration: 86400000
  refreshExpiration: 604800000

iamport:
  key: 6625177213832842
  secret: fQcJVhbwGTVi5EFHMnfmhS288WdJDgJ0U5yDHAmbos92MltOfSrBdBZQCWxexlCXK95oxdciZSEdOsId